name: Build
run-name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Lua
        uses: hishamhm/gh-actions-lua@master
        with:
          luaVersion: 5.4
      - name: Install LuaRocks
        uses: hishamhm/gh-actions-luarocks@master
      - name: Install cyan
        run: luarocks install cyan
      - name: Install just
        run: |
          wget https://github.com/casey/just/releases/download/1.39.0/just-1.39.0-x86_64-unknown-linux-musl.tar.gz
          tar -xzf just-1.39.0-x86_64-unknown-linux-musl.tar.gz just
          cp just /usr/local/bin
          just --version
      - name: Typecheck and build
        run: |
          just dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openmw_markers
          path: dist
